In [26]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
import time

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
filepath = '/content/drive/MyDrive/AI ML/IRP/datasets/adult_dataset.csv'
df_adult = pd.read_csv(filepath)
df_adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39.0,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40.0,NaN,<=50K
1,50.0,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13.0,United-States,<=50K
2,38.0,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40.0,United-States,<=50K
3,53.0,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40.0,United-States,<=50K
4,28.0,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40.0,Cuba,<=50K

In [29]:
df_adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             46400 non-null  float64
 1   workclass       45480 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      45485 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  46400 non-null  float64
 13  native-country  46137 non-null  object
 14  income          48842 non-null  object
dtypes: float64(2), int64(4), object(9)
memory usage: 5.6+ MB

In [30]:
df_adult.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,46400.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,46400.000000
mean,38.679116,1.896641e+05,10.078089,1079.067626,87.502314,40.448599
std,13.952954,1.056040e+05,2.570973,7452.019058,403.004552,12.646992
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,255.000000,1.490400e+06,16.000000,99999.000000,4356.000000,250.000000

In [31]:
df_adult.duplicated().sum()

np.int64(16)

In [32]:
df_adult.drop_duplicates(inplace = True)

In [33]:
df_adult.isna().sum()

age               2442
workclass         3362
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        3357
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week    2442
native-country    2705
income               0
dtype: int64

In [34]:
num_cols = df_adult.select_dtypes(include=['int64', 'float64']).columns
num_cols

Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week'],
      dtype='object')

In [35]:
cat_cols = df_adult.select_dtypes(include=['object']).columns
cat_cols

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country', 'income'],
      dtype='object')

In [36]:
print("Numeric missing:\n", df_adult[num_cols].isna().sum())
print("\nCategorical missing:\n", df_adult[cat_cols].isna().sum())

Numeric missing:
 age               2442
fnlwgt               0
education-num        0
capital-gain         0
capital-loss         0
hours-per-week    2442
dtype: int64

Categorical missing:
 workclass         3362
education            0
marital-status       0
occupation        3357
relationship         0
race                 0
sex                  0
native-country    2705
income               0
dtype: int64

In [37]:
# median for numeric, mode for categorical
for col in num_cols:
    df_adult[col] = df_adult[col].fillna(df_adult[col].median())

for col in cat_cols:
    df_adult[col] = df_adult[col].fillna(df_adult[col].mode()[0])

## Encoding

In [38]:
# label encoding here because there are only two values
label_sex = LabelEncoder()
df_adult['sex'] = label_sex.fit_transform(df_adult['sex'])

label_income = LabelEncoder()
df_adult['income'] = label_income.fit_transform(df_adult['income'])

In [39]:
df_adult.head(2)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39.0,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,1,2174,0,40.0,United-States,0
1,50.0,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,13.0,United-States,0

In [40]:
one_hot_columns = [
    'workclass'
    'marital-status'
    'occupation'
    'relationship'
]

df_adult = pd.get_dummies(
    df_adult,
    drop_first=True,
    dtype=int
)

In [41]:
df_adult.head(2)

,age,fnlwgt,education-num,sex,capital-gain,capital-loss,hours-per-week,income,workclass_Federal-gov,workclass_Local-gov,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,39.0,77516,13,1,2174,0,40.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,50.0,83311,13,1,0,0,13.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

## Train Test Split

In [42]:
X = df_adult.drop('income', axis=1)
y = df_adult['income']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (39060, 100)
X_test: (9766, 100)
y_train: (39060,)
y_test: (9766,)

## Scaling

In [43]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Tensorflow

In [44]:
tf.random.set_seed(42)

model_tf = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(100,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

model_tf.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'],
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [45]:
start_time = time.perf_counter()

history = model_tf.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

end_time = time.perf_counter()

print(f"Training Time: {end_time - start_time:.4f} seconds")

Epoch 1/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 13s 10ms/step - accuracy: 0.3680 - loss: -737.4883 - val_accuracy: 0.3816 - val_loss: -3085.5259
Epoch 2/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3751 - loss: -10640.1738 - val_accuracy: 0.3815 - val_loss: -21765.5332
Epoch 3/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3670 - loss: -40075.3008 - val_accuracy: 0.2869 - val_loss: -63155.3594
Epoch 4/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.3652 - loss: -94842.4922 - val_accuracy: 0.3939 - val_loss: -132317.1719
Epoch 5/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3651 - loss: -178655.1094 - val_accuracy: 0.3900 - val_loss: -231801.6719
Epoch 6/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3644 - loss: -294146.1562 - val_accuracy: 0.3831 - val_loss: -364475.1562
Epoch 7/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.3626 - loss: -444232.8750 - val_accuracy: 0.3831 - val_loss: -533322.7500
Epoch 8/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.3618 - loss: -631934.6875 - val_accuracy: 0.3849 - val_loss: -741393.6875
Epoch 9/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3610 - loss: -860330.9375 - val_accuracy: 0.3863 - val_loss: -991770.6875
Epoch 10/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.3627 - loss: -1132514.2500 - val_accuracy: 0.4009 - val_loss: -1287578.7500
Epoch 11/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.3612 - loss: -1451585.0000 - val_accuracy: 0.3774 - val_loss: -1631921.2500
Epoch 12/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.3628 - loss: -1820632.0000 - val_accuracy: 0.3939 - val_loss: -2027868.2500
Epoch 13/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.3617 - loss: -2242726.0000 - val_accuracy: 0.3826 - val_loss: -2478531.0000
Epoch 14/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.3601 - loss: -2720921.0000 - val_accuracy: 0.3957 - val_loss: -2986936.5000
Epoch 15/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.3615 - loss: -3258263.5000 - val_accuracy: 0.3959 - val_loss: -3556081.7500
Epoch 16/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.3586 - loss: -3857770.0000 - val_accuracy: 0.3980 - val_loss: -4189076.2500
Epoch 17/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.3606 - loss: -4522489.0000 - val_accuracy: 0.3931 - val_loss: -4888907.5000
Epoch 18/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.3607 - loss: -5255415.5000 - val_accuracy: 0.3743 - val_loss: -5658523.5000
Epoch 19/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3587 - loss: -6059508.5000 - val_accuracy: 0.3797 - val_loss: -6500993.0000
Epoch 20/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3600 - loss: -6937775.0000 - val_accuracy: 0.3986 - val_loss: -7419217.5000
Epoch 21/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3606 - loss: -7893157.5000 - val_accuracy: 0.3954 - val_loss: -8416142.0000
Epoch 22/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3572 - loss: -8928602.0000 - val_accuracy: 0.3360 - val_loss: -9494850.0000
Epoch 23/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3597 - loss: -10047096.0000 - val_accuracy: 0.3964 - val_loss: -10658208.0000
Epoch 24/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.3609 - loss: -11251588.0000 - val_accuracy: 0.3964 - val_loss: -11909154.0000
Epoch 25/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3597 - loss: -12545009.0000 - val_accuracy: 0.3938 - val_loss: -13250706.0000
Epoch 26/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3601 - loss: -13930276.0000 - val_accuracy: 0.3100 - val_loss: -14685747.0000
Epoch 27/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3598 - loss: -15410345.0000 - val_accuracy: 0.3443 - val_loss: -16217237.0000
Epoch 28/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.3581 - loss: -16988156.0000 - val_accuracy: 0.2724 - val_loss: -17848068.0000
Epoch 29/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3578 - loss: -18666546.0000 - val_accuracy: 0.3987 - val_loss: -19581118.0000
Epoch 30/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.3579 - loss: -20448472.0000 - val_accuracy: 0.3985 - val_loss: -21419414.0000
Epoch 31/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.3623 - loss: -22336834.0000 - val_accuracy: 0.3994 - val_loss: -23365740.0000
Epoch 32/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3561 - loss: -24334554.0000 - val_accuracy: 0.3949 - val_loss: -25423072.0000
Epoch 33/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.3594 - loss: -26444506.0000 - val_accuracy: 0.4007 - val_loss: -27594328.0000
Epoch 34/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3615 - loss: -28669636.0000 - val_accuracy: 0.3949 - val_loss: -29882344.0000
Epoch 35/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3603 - loss: -31012782.0000 - val_accuracy: 0.4009 - val_loss: -32290058.0000
Epoch 36/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3619 - loss: -33476928.0000 - val_accuracy: 0.3949 - val_loss: -34820484.0000
Epoch 37/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3595 - loss: -36064856.0000 - val_accuracy: 0.4005 - val_loss: -37476284.0000
Epoch 38/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3598 - loss: -38779492.0000 - val_accuracy: 0.3978 - val_loss: -40260544.0000
Epoch 39/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3594 - loss: -41623728.0000 - val_accuracy: 0.3025 - val_loss: -43176028.0000
Epoch 40/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3591 - loss: -44600364.0000 - val_accuracy: 0.3958 - val_loss: -46225504.0000
Epoch 41/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3606 - loss: -47712344.0000 - val_accuracy: 0.3038 - val_loss: -49412272.0000
Epoch 42/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3590 - loss: -50962584.0000 - val_accuracy: 0.3999 - val_loss: -52738840.0000
Epoch 43/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3590 - loss: -54353848.0000 - val_accuracy: 0.4048 - val_loss: -56208096.0000
Epoch 44/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3612 - loss: -57888888.0000 - val_accuracy: 0.2793 - val_loss: -59822800.0000
Epoch 45/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3601 - loss: -61570696.0000 - val_accuracy: 0.3575 - val_loss: -63586196.0000
Epoch 46/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.3580 - loss: -65402336.0000 - val_accuracy: 0.3836 - val_loss: -67501048.0000
Epoch 47/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3590 - loss: -69386608.0000 - val_accuracy: 0.3962 - val_loss: -71570160.0000
Epoch 48/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3597 - loss: -73526088.0000 - val_accuracy: 0.2706 - val_loss: -75796200.0000
Epoch 49/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3586 - loss: -77824024.0000 - val_accuracy: 0.4040 - val_loss: -80182304.0000
Epoch 50/50
977/977 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3580 - loss: -82283104.0000 - val_accuracy: 0.3826 - val_loss: -84731568.0000
Training Time: 219.8920 seconds

In [47]:
loss,accuracy = model_tf.evaluate(X_test,y_test)

print("Accuracy :",accuracy)

306/306 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3738 - loss: -84762672.0000
Accuracy : 0.3738480508327484

## Pytorch

In [48]:
import torch
import torch.nn as nn
import torch.optim as optim

In [50]:
# convert every data to tensor
X_train_tensor = torch.FloatTensor(X_train)

X_test_tensor = torch.FloatTensor(X_test)

y_train_tensor = torch.FloatTensor(y_train.values.reshape(-1,1))

y_test_tensor = torch.FloatTensor(y_test.values.reshape(-1,1))

In [56]:
class ANN(nn.Module):
  def __init__(self):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(100,64),
        nn.ReLU(),
        nn.Linear(64,32),
        nn.ReLU(),
        nn.Linear(32,1),
        nn.Sigmoid()
    )

  def forward(self,x):
    return self.network(x)

In [52]:
model = ANN()

In [53]:
criterion = nn.BCELoss()

In [54]:
optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

In [60]:
start_time = time.perf_counter()
epochs = 50
for epoch in range(epochs):
   outputs = model(X_train_tensor)
   loss = criterion(outputs, current_y_train_tensor)
   optimizer.zero_grad()
   loss.backward()
   optimizer.step()
   if(epoch+1)%10 ==0:
    print(f"Epoch{epoch+1}",f"Loss={loss.item():.4f}")
end_time = time.perf_counter()

print(f"Training time  : {end_time - start_time:.4f} seconds")

Epoch10 Loss=0.6759
Epoch20 Loss=0.6545
Epoch30 Loss=0.6362
Epoch40 Loss=0.6240
Epoch50 Loss=0.6164
Training time  : 3.7087 seconds